# Generated by Django 2.2.4 on 2019-08-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='number',
            field=models.IntegerField(),
        ),
    ]
